unit Unit2;

interface

uses
 jpeg, Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ExtCtrls, StdCtrls, Mmsystem, ShellAPI, Unit1;

const len = 30;
      maxplayers = 10;

type
  TForm2 = class(TForm)
    Label1: TLabel;
    Button1: TButton;
    Label2: TLabel;
    Label5: TLabel;
    Button3: TButton;
    Label6: TLabel;
    Label7: TLabel;
    Edit2: TEdit;
    Button4: TButton;
    Button5: TButton;
    Label8: TLabel;
    Image1: TImage;
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure Image1Click(Sender: TObject);
    procedure Button5Click(Sender: TObject);
 //   procedure reset1(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

type lrec = record
                     a:integer;
                     s:string;
                  end;

type smas = array[1..21] of lrec;

var
  Form2: TForm2;
  f:textfile;
  A:smas;
  i:integer;

implementation


{$R *.dfm}


function improve(s:string; x:integer):string;
var i,j,l,q:integer;
begin
    q:=0;
    for i:=1 to length(s) do
      if (s[i]=' ') then q:=q+1;
    l:=len - length(s) -q - length(inttostr(x)) - 2;
    s:=s+' ';
    for i:=1 to l do s:=s+'-';
    s:=s+' ';
    s:=s+inttostr(x);
    improve:=s;
end;

function sort(A:smas; n:integer):smas;
var i,j:integer;
    b:boolean;
    s:string;
begin
    b:=true;
    while (b) do
    begin
        b:=false;
        for i:=1 to (n-1) do
        begin
            if (A[i].a < A[i+1].a) then
            begin
                j:=A[i].a;
                s:=A[i].s;
                A[i]:=A[i+1];
                A[i+1].a:=j;
                A[i+1].s:=s;
                b:=true;
            end;
        end;
    end;
    sort:=A;
end;

function reverse(s:string):string;
var i:integer;
    z:string;
begin
    z:='';
    for i:=length(s) downto 1 do z:=z+s[i];
    reverse:=z;
end;

procedure save;
var x,n,i:integer;
    s,c,name:string;
begin
    x:=strtoint(Form2.Label8.Caption);
    name:=Form2.Edit2.Text;
    if (name='') then
    begin
        showmessage('If you want to save score, write your name');
        exit;
    end;
    assignfile(f, 'scores.txt');
    reset(f);
    readln(f,s);
    n:=0;
    while (not(eof(f))) do
    begin
        n:=n+1;
        readln(f,s);
        i:=length(s);
        c:='';
        while (s[i]<>' ') do
        begin
            c:=c+s[i];
            i:=i-1;
        end;
        c:=reverse(c);
        A[n].a:=strtoint(c);
        A[n].s:=s;
    end;
    closefile(f);
    A[n+1].a:=x;
    A[n+1].s:=improve(name,x);
    A:=sort(A,n+1);
    assignfile(f,'scores.txt');
    rewrite(f);
    n:=n+1;
    writeln(f,'** Please, do not edit this file **');
    if (n>=maxplayers) then
    begin
        for i:=1 to (maxplayers-1) do
        writeln(f,A[i].s);
        write(f,A[maxplayers].s);
    end else
    begin
        for i:=1 to (n-1) do
        writeln(f,A[i].s);
        write(f,A[n].s);
    end;
    closefile(f);
    Form2.Button3.Visible:=false;
    Form2.Label6.Visible:=true;
end;

procedure TForm2.Button1Click(Sender: TObject);
begin
    Form1.Visible:=true;
    Form1.Button1Click(Form1.Button1);
    Form2.Button3.Visible:=true;
    Form2.Label6.Visible:=false;
    Form2.Visible:=false;
end;

procedure TForm2.Button2Click(Sender: TObject);
begin
    Form1.Close;
    form2.Close;
end;

procedure TForm2.Button3Click(Sender: TObject);
begin
    save;
end;

procedure TForm2.Button4Click(Sender: TObject);
var  s,c:string;
     f:textfile;
     i,j:integer;
begin
    assignfile(f,'scores.txt');
    reset(f);
    readln(f);
    c:='';
    for i:=1 to 17 do
    begin
        c:=c+#32;
    end;
    c:=c+'HIGHSCORES';
    i:=0;
    while (not(eof(f))) do
    begin
        i:=i+1;
        c:=c+#13;
        readln(f,s);
     {   j:=1;
        while (j<length(s)) do
        begin
           if ((s[j]=' ') and (s[j+1]=' ')) then
           begin
               s[j]:=#32;
               s[j+1]:=#32;
               j:=j+2;
           end else j:=j+1;
        end;  }

        if (i<10) then c:=c + '0'+inttostr(i) + #32#32 + s else
                       c:=c+inttostr(i) + #32#32 + s;
    end;
    if (i=0) then c:=#32#32#32#32#32#32#32#32#32#32#32#32#32#32 + 'NO SCORES YET';
    showmessage(c);
    closefile(f);
end;

procedure TForm2.FormClose(Sender: TObject; var Action: TCloseAction);
begin
   Form1.Close;
end;

procedure TForm2.Image1Click(Sender: TObject);
var c:string;
begin
     c:=#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32 + 'ABOUT:'+#13#13;
     c:=c+'Now working on monsters.'+#13+'If you have suggestions, please, contact the author.' +#13+ 'suvidrov@gmail.com' + #13 +  'Hope you like the game!'+#13;
     c:=c+'-------------------------------------------'+#13;
     c:=c+'Written on Delphi 7. Gift edition.';
     showmessage(c);
end;

procedure TForm2.Button5Click(Sender: TObject);
var c:string;
begin
     c:=#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32#32 + 'INSTRUCTIONS:'+#13#13;
     c:=c+'mouse - to move'+#13;
     c:=c+'Left mouse click - to shoot'+#13;
     c:=c+'Right mouse click - pause'+#13;
     c:=c+'--------------------------------------'+#13;
     //c:=c+'You could notice some flickering.'+#13;
     c:=c+ 'working on this.'+#13;
     c:=c+'--------------------------------------'+#13;
     c:=c+'Click on gift for "About" '+#13#13;
     c:=c + 'Sound works. Take your headphones!'+#13#13;
     showmessage(c);
end;

end.
